### ISSUE TITLE
Feature Suggestion: Just output the encrypted password, without writing into .travis.yml

### ISSUE THREAD

**Issue by rayluo** [mandeep/Travis-Encrypt#1]
Hi @mandeep , thanks for sharing this Travis-Encrypt. Its much slimer code base makes it much easier to audit.

I would like to suggest a new feature as "Just output the encrypted password, without writing into .travis.yml". Something like this:

    usage: travis-encrypt [options] github_username repository

    positional arguments:
        github_username         GitHub username that houses the repository
        repository              Name of the repository whose password requires encryption

    optional arguments:
        --password TEXT     If absent, you will be prompted for a password, which will then
                                        be encrypted and printed to stdout.

Example:

    $ travis-encrypt your_github_account your_github_repo 'plain-text-password'
    Please add the following to your .travis.yml file:
        secure: "encrypted-password-string"

The rationale behind this suggested new behavior:

* When I'm trying to follow [this post](https://www.appneta.com/blog/pypi-deployment-with-travis-ci/) to setup automated PyPI deployment for my project, the "deploy" section will be a list, not a dictionary, therefore the current travis-encrypt 0.3.3 will fail with exception: `AttributeError: 'list' object has no attribute 'setdefault'`.

* The current travis-encrypt 0.3.3 implementation actually requires a valid, non-empty yml file to exist (which then has to be handwritten beforehand), and then it will overwrite such file with a side effect of changing the settings appearance order. This would end up with a confusing commit, which can be somewhat annoying.

To solve the above two pain points, it seems a minimal design will be better. The proposed new behavior only provided the encrypted string, let the user to add it into his/her yml file, just as what the original travis client does.

PS: You can keep the other existing travis-entrypt parameters (`path`, `--deploy`, `--env`) and their behaviors if you really prefer, but I would even go one step further to remove them.

**Comment by mandeep** [comment]
Hi @rayluo! Thanks for your compliments on Travis-Encrypt and sorry to hear about your troubles deploying to PyPI. I agree that an output to terminal should be the default setting. I can't remember now why I chose not to go down that route, however I will start working on this feature and hope to merge it today or sometime this weekend.

**Comment by mandeep** [comment]
@rayluo I've pushed 0.4.0 that now defaults to printing the encrypted password to standard output. There are a few small formatting matters that I think need to be addressed, but I need time to think about how I want to approach them. In the meantime please let me know if you have any other concerns, I'm happy to address them.

**Comment by rayluo** [comment]
I'll definitely try it out, although I don't really have a release plan for my own project at this moment.

A quick question. Does [the `!!binary |` part and the ascii-decoding and the base64-encoding](https://github.com/mandeep/Travis-Encrypt/blob/0.4.1/travis/encrypt.py#L81) really necessary? You did not do that [previously](https://github.com/mandeep/Travis-Encrypt/blob/0.4.1/travis/encrypt.py#L67-L73). Nor am I seeing such pattern in other [sample repo](https://github.com/danriti/python-traceview/blob/master/.travis.yml#L20).

**Comment by mandeep** [comment]
When writing to yaml, pyyaml will encode the bytes as base64 and add the binary!! | tag. Since pyyaml defaults to this behavior, manually encoding to base64 is unneeded. The documentation does a better job of explaining it if you're interested: [yaml.org/type/binary.html](url). 

To print to standard output, I wanted to emulate pyyaml's behavior. I needed to encode to base64, however if I printed the encoded base64 string to stdout, the password word be wrapped around b"". To print the password as text instead of a bytes object, I decided to decode to ascii since the base64 code points fall into ascii's code points. I would like to remove the need for the binary!! | tag, however it will take further digging into the travis documentation.

**Comment by mandeep** [comment]
Pondering about my previous explanation, I realized all that's needed is an ascii representation of the base64 bytes object. Therefore, I decode to ascii upon creation of the encrypted password in the encrypt_key function. Now, there is no need for the binary tag and hopefully everything works as expected. Thanks @rayluo for helping me think about this. :smiley:

**Comment by rayluo** [comment]
It looks better this time. :)  Thanks!

One minor minor issue. You'd better encode that [yaml binary spec](http://yaml.org/type/binary.html) in your previous comment. Right now github does not render it as a corrent link.

**Comment by mandeep** [comment]
Thanks!
