### ISSUE TITLE
travis-ci.com support

### ISSUE THREAD

**Issue by earonesty** [mandeep/Travis-Encrypt#13]
As of May 2018 all new projects must be on `travis-ci.com`.  Apis for .org won't work on these projects.    Need to add "--org/--com" options to  the command line tool, and/or try twice (falling back to legacy?).

See: https://blog.travis-ci.com/2018-05-02-open-source-projects-on-travis-ci-com-with-github-apps

**Comment by mandeep** [comment]
Hi @earonesty, I'm not sure I understand. The blog is dated from last year but the .org domain still seems to work. Are you seeing problems with the .org API?

**Comment by mandeep** [comment]
I realize now that travis-encrypt only works for open source projects, and if we want to access .com projects we need an option for this.

**Comment by mandeep** [comment]
So as to not break the `encrypt.py` API, I think we need to add another function that does the same thing as `retrieve_public_key` but for the .com API endpoint. 

https://github.com/mandeep/Travis-Encrypt/blob/0dd2da1c71feaadcb84bdeb26827e6dfe1bd3b41/travis/encrypt.py#L21
