### ISSUE TITLE
Python versions supported by Travis-Encrypt

### ISSUE THREAD

**Issue by JoelMon** [mandeep/Travis-Encrypt#20]
Quick question, what versions of Python do you want to be supported by Travis-Encrypt?

test_cli.py imports mock which is a 2.x thing but encrypt.py uses prints() which are not supported by 2.x.

**Comment by mandeep** [comment]
print() is supported by 2.7 which is the highest Python 2 version supported. The versions listed in setup.py are the officially supported version by this application.

**Comment by JoelMon** [comment]
Gotcha. Thanks
