### ISSUE TITLE
Support access token for public key retrieval

### ISSUE THREAD

**Issue by tasptz** [mandeep/Travis-Encrypt#23]
Key retrieval for me only works with the access token:
https://docs.travis-ci.com/user/encryption-keys/#examples
`curl -H "Authorization: token **TOKEN**" https://api.travis-ci.com/v3/repo/OWNER%2fREPO/key_pair/generated`

Maybe because I switched the repository from private to public.

**Comment by mandeep** [comment]
@tasptz thanks for the issue report. If I understand correctly, you're looking for the ability to retrieve the public key with `travis-encrypt`?

**Comment by tasptz** [comment]
Yes, correct.

**Comment by mandeep** [comment]
Thanks, I'll see if I can add this.

**Comment by mandeep** [comment]
I believe this was added in commit 114bc67f4431915d662ce4ba688ad02cdcff3da6
